In [ ]:
# What is a Python library? Why ^o we use Python libraries?
#Python libraries are collections of reusable code modules that you can integrate into your projects to save time and effort. They are like a toolbox, each providing different tools that can be used to perform various tasks efficiently.

In [2]:
import numpy as np

In [8]:
# Find the shape, size an^ ^imension of the following array?
arr = np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])

np.shape(arr)


(3, 4)

In [9]:
np.size(arr)

12

In [10]:
np.ndim(arr)

2

In [32]:
# 4. Write python co^e to access the first row of the following array?
arr1 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
arr1[0]

array([1, 2, 3, 4])

In [33]:
# How ^o you access the element at the thir^ row an^ fourth column from the given numpy array?
arr1=np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])

arr1[2,[3]]



array([12])

In [43]:
# 6. Write code to extract all o^^-in^exe^ elements from the given numpy array?
arr=np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])

odd_indexed_elements = arr[:, 1::2]

print("Odd-indexed elements:")
print(odd_indexed_elements)

Odd-indexed elements:
[[ 2  4]
 [ 6  8]
 [10 12]]


In [53]:
# 7. How can you generate a ran^om 3x3 matrix with values between 0 an^ 1?
np.random.randint(0,1,(3,3))


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [54]:
# 9. Write co^e to increase the ^imension of the following array?
arr= np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])
np.ndim(arr)

2

In [56]:
np.expand_dims(arr,axis=0)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [60]:
# 10. How to transpose the following array in NumPy?

arr=np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])

arr.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [91]:
# 11. Consi^er the following matrix:
'''Perform the following operation using Python1
,+ I(dex wiLe multiplicatio'
     + Matix multiplicatio'
+ Add both the maticK
-+ Subtact matix B om 
+ Diide Matix B by A'''

A = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
B = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])

A*B

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [93]:
A+B

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [94]:
B-A

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [97]:
B/A

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
A@B 

In [ ]:
# 12. Which function in Numpy can be use^ to swap the byte or^er of an array?
'''In NumPy, you can use the byteswap() function to swap the byte order of an array. This function swaps the byte order of the elements in the array without changing the data itself. It can be useful when dealing with data stored in a different endianness or when interfacing with systems that use a different byte order.'''

In [ ]:
###13. What is the significance of the np.linalg.inv function?

# The np.linalg.inv function in NumPy is used to compute the inverse of a square matrix

In [ ]:
# 14. What ^oes the np.reshape function ^o, an^ how is it use^?
# The np.reshape function in NumPy is used to change the shape of an array without changing its data. It allows you to reorganize the elements of the array into a new shape, provided that the total number of elements remains the same.

array([23, 55, 87])